# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 50000
mask_before_softmax: False

runner: "parallel"

buffer_size: 2
batch_size_run: 2
batch_size: 2

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "c_coma"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "C-COMA"

useMultiHeadAttention: True

hypernet_embed: 128
mixing_embed_dim: 32
softmax_mixing_weights: True
attn_embed_dim: 128

agent: "rnn"

attn_n_heads: 4

mac: "basic_mac"

mode_type : 1

# True : 지속학습(신경망의 일부만 갱신), False 일반적인 학습 (신경망 전체 갱신)
Is_continuous_learning : True

